### ISSUE TITLE
更新数据后，其他机器上的一级缓存，没有同步更新，造成数据不一致

### ISSUE THREAD

**Issue by 15986724700** [xiaolyuh/layering-cache#1]
request 请求到其中一台服务器更新的一级缓存就是本机的一级缓存，其他机器的一级缓存并没有更新.如果请求转发到其他机器上，会不会数据不同步。

**Comment by xiaolyuh123** [comment]
不会，基于redis的pub/sub来做的一级缓存更新，所以其他机器也会更新

**Comment by 15986724700** [comment]
v1.6 源码里面只有删除的时候有pub/sub，更新的时候是没有的

**Comment by xiaolyuh123** [comment]
首先非常感谢你的意见。这个put方法我最初设计只是往缓存里面放值，不是用于更新的。如果需要更新是先要删除,在放入。但是这个方法确实有歧义，我会在下一个版本修改，在put的时候先放二级缓存，在清空一级缓存。这样即使将put作为更新方法也不会有问题。

**Comment by 15986724700** [comment]
请教个问题，我怎么用layering-cache 对分页列表进行缓存，这个列表有多个可以排序的字段。比如，按价格正序/倒序。按销量正序/倒序。

**Comment by xiaolyuh123** [comment]
在被缓存的方法上加一个参数表示使用什么字段排序。然后将这个字段作为缓存的一个key

**Comment by 15986724700** [comment]
这些查询条件还有多种组合方式呢。那这样在商品更新或者删除的时候，都需要去同步维护这些缓存。工作量有点大
