### ISSUE TITLE
pub/sub模式是没有实现么

### ISSUE THREAD

**Issue by cuidd2018** [xiaolyuh/layering-cache#100]
[#90 ](https://github.com/xiaolyuh/layering-cache/issues/90)
![20240614152755](https://github.com/xiaolyuh/layering-cache/assets/35174463/70ad25e6-5767-4fb0-8a16-3bc6f4af9635)

` public static void publisher(RedisClient redisClient, RedisPubSubMessage message, String nameSpace) {
        String messageJson = JSON.toJSONString(message);
        // pull 拉模式消息
        redisClient.lpush(GlobalConfig.getMessageRedisKey(nameSpace), GlobalConfig.GLOBAL_REDIS_SERIALIZER, messageJson);
        redisClient.expire(GlobalConfig.getMessageRedisKey(nameSpace), 25, TimeUnit.HOURS);
        // pub/sub 推模式消息
        redisClient.publish(RedisMessageListener.CHANNEL, "m");
        if (logger.isDebugEnabled()) {
            logger.debug("redis消息发布者向频道【{}】发布了【{}】消息", RedisMessageListener.CHANNEL, message.toString());
        }
    }`

**Comment by xiaolyuh123** [comment]
这里的m是表标识，信息在队列里面
