### ISSUE TITLE
FirstCache 默认开启问题

### ISSUE THREAD

**Issue by icemoff** [xiaolyuh/layering-cache#18]
> @Cacheable(value = "user:info", depict = "用户信息缓存",
		secondaryCache = @SecondaryCache(expireTime = 10, preloadTime = 3, forceRefresh = true, timeUnit = TimeUnit.SECONDS))

代码里只开启了 @SecondaryCache，但观测FirstCache 默认开启。
导致其实SecondaryCache(redis)已经过期不存在了，结果还是走了缓存方法(FirstCache)
请问下怎么关闭掉默认行为（不想使用一级缓存）

**Comment by xiaolyuh123** [comment]
目前没法，为什么要关闭呢


发自我的iPhone

**Comment by icemoff** [comment]
用一级缓存和二级缓存应该是项目场景上考虑的事情，正常一些场景用redis缓存就够了，更高的性能要要求才考虑会组合使用一二级缓存（个人认为会让数据存储的维度多一层，定位问题更难）。
放在redis的可观测，可修改，可手动db删除，大多数下我用它就行了。

**Comment by icemoff** [comment]
> 目前没法，为什么要关闭呢 发自我的iPhone
> […](#)
> 在 2020年5月9日，上午9:09，icemoff ***@***.***> 写道： ﻿ 代码里只开启了 @SecondaryCache，但观测FirstCache 默认开启，请问下怎么关闭掉默认行为 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xiaolyuh123** [comment]
你直接将一级缓存的时间设置得很小就行了啊
