### ISSUE TITLE
不支持反序列化的对象类型

### ISSUE THREAD

**Issue by wanbeiapp** [xiaolyuh/layering-cache#19]
com.github.xiaolyuh.support.SerializationException: FastJsonRedisSerializer 反序列化异常: autoType is not support. org.springframework.data.domain.PageImpl

**Comment by xiaolyuh123** [comment]
https://xiaolyuh.blog.csdn.net/article/details/78679030
















在 2020-06-06 11:30:17，"wanbeiapp" <notifications@github.com> 写道：

com.github.xiaolyuh.support.SerializationException: FastJsonRedisSerializer 反序列化异常: autoType is not support. org.springframework.data.domain.PageImpl
