### ISSUE TITLE
junit测试时发现redis缓存清空失败

### ISSUE THREAD

**Issue by sandogeek** [xiaolyuh/layering-cache#2]
debug发现：重新启动测试时,layring cache没有读取redis所有缓存名称，所以清空指定名称缓存时没有找到这个缓存，就没有对redis内的缓存做清空操作

**Comment by xiaolyuh123** [comment]
重启时是不会读取缓存名称的，也不会去清空缓存，这个建议我会再做考虑看怎么优化一下。

**Comment by xiaolyuh123** [comment]
您好非常感谢你的意见，您反馈的问题已经在1.1.9版本修复了。
