### ISSUE TITLE
关于value注解不支持SpEl表达式的疑问

### ISSUE THREAD

**Issue by qinchz** [xiaolyuh/layering-cache#26]
你好，我看最新代码里面去掉了value注解支持SpEl的逻辑，为什么呢？我在实际使用过程中，有在value中使用变量传入的场景，用来缩小删除缓存的范围。

**Comment by xiaolyuh123** [comment]
没有去掉咋

发自我的iPhone

**Comment by qinchz** [comment]
![Screenshot_20201006_074001_com.huawei.browser.jpg](https://user-images.githubusercontent.com/18414101/95143103-d33f3580-07a7-11eb-83db-50b60e919760.jpg)
![Screenshot_20201006_074038_com.huawei.browser.jpg](https://user-images.githubusercontent.com/18414101/95143116-d9351680-07a7-11eb-9fcb-4225119d351e.jpg)

**Comment by xiaolyuh123** [comment]
这是缓存名称  不是value

**Comment by xiaolyuh123** [comment]
![image](https://user-images.githubusercontent.com/5269727/95698938-bdcd7e00-0c75-11eb-8429-9ac2435e3226.png)

**Comment by qinchz** [comment]
是的，key是支持我是知道的。问题就在这，cacheName有些场景也是需要支持SPEL表达式的，因为有些方法在清除缓存的时候，只能给很简单的参数（给不到key那么多），确定一个大致范围，这时候就清除缓存时，不指定key，指定一个带参数的className，会很方便
