### ISSUE TITLE
关于执行forceRefresh不清除一级缓存的疑问

### ISSUE THREAD

**Issue by qinchz** [xiaolyuh/layering-cache#27]
您好，有以下问题请教下：
1、在设置了preloadTime参数，并指定forceRefresh=true，会跑异步线程进行二级缓存更新。但是我注意到好像在更新二级缓存时，没有push消息进行一级缓存更新，这样设计是出于对性能的考虑吗？
2、基于上面的场景，有些内容对于失效时间有较为严格的要求（例如播放地址过期即无法使用），上面的情况如果发生在边界时间（二级缓存即将过期，重建了一级缓存），则需要再等一个完整的一级缓存过期时间，才能拿到最新的二级缓存，会导致很长一段时间拿到的播放地址都是不可用的。一级缓存时间设置的足够小，可以解决此问题，但这样没有完全发挥出一级缓存的作用

**Comment by xiaolyuh123** [comment]
1. 因为每次刷新缓存，获取到的数据不一定会更新，所以不是每次刷新都会push消息进行一级缓存的更新，这个问题后面的版本可以考虑看怎么优化下不。
2. 这个就只能靠设置准确的失效时间和刷新时间来避免。

**Comment by xiaolyuh123** [comment]
第一点我已经在3.1.6版本做了优化，如果刷新二级缓存的时候发现数据发生变化就更新一级缓存
