### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by webwangbao** [xiaolyuh/layering-cache#3]
今天测试了一下作者的这个缓存框架，挺好的，有个小建议哈，redis原生的消息发布订阅模式作为消息队列并不是很好，并且消费的顺序性不确定，所以在分布式的情况下一级缓存的更新可能会出现更新不及时甚至更新失败的情况，希望在下个版本可以看见作者更加优秀的表现！

**Comment by xiaolyuh123** [comment]
非常感谢你的建议，我会认真考虑一下的，谢谢了

**Comment by xiaolyuh123** [comment]
你好，个人觉得使用redis来做为消息队列没什么问题。1. 使用缓存本来就允许脏读，所以有一定的延迟是允许的  2. redis本身是一个高可用的数据库，并且删除动作不是一个非常频繁的动作所以使用redis原生的发布订阅是没有问题的
