### ISSUE TITLE
关于自动刷新的疑似bug

### ISSUE THREAD

**Issue by qinchz** [xiaolyuh/layering-cache#30]
这里调用清除一级缓存时，好像没有判断是否开启了一级缓存（enableFirstCache）。

https://github.com/xiaolyuh/layering-cache/blob/462bd52cdee485325e0a5e7d9522082b0092d88e/layering-cache-core/src/main/java/com/github/xiaolyuh/cache/redis/RedisCache.java#L345-L349

**Comment by xiaolyuh123** [comment]
这里不判断也没啥问题的
