### ISSUE TITLE
建议把将fastjson的依赖彻底去掉，需要的时候再引入

### ISSUE THREAD

**Issue by MayBeWrong** [xiaolyuh/layering-cache#33]
问题：
将fastjson的依赖彻底去掉
现象：
没用到fastjson但是还必须引入，这个不方便，建议全局optional引入。
用conditional条件表达式判断是fastjson还是jackson，有哪个用哪个
灰常敢射！

**Comment by xiaolyuh123** [comment]
框架本身很多地方用了fastJson，去掉fastjson的引用带来的收益并不是很大
