### ISSUE TITLE
为何要在3.0版本去掉RedisTemplate

### ISSUE THREAD

**Issue by JunlinHe** [xiaolyuh/layering-cache#34]
如题，请问是否RedisTemplate有什么坑吗

**Comment by xiaolyuh123** [comment]
有些系统不使用redistemplate.有些系统会使用多个redistemplate.去点过后可以减少依赖和冲突的可能

发自我的iPhone

**Comment by JunlinHe** [comment]
🤞先入为主了，谢谢大佬的经验
