### ISSUE TITLE
能否禁用二级缓存

### ISSUE THREAD

**Issue by hdtopku** [xiaolyuh/layering-cache#36]
有些场景只需要短暂内存缓存几秒，无需redis缓存，可以用自带的@Cacheable本地缓存，不过没有过期时间，不方便。
请问如何只使用一级缓存，禁用二级缓存？

**Comment by xiaolyuh123** [comment]
二级缓存时间设置为0


发自我的iPhone

**Comment by hdtopku** [comment]
感谢
