### ISSUE TITLE
layering-cache 的 redis 配置和 springboot 的 redis 重复

### ISSUE THREAD

**Issue by rexzhaoxb** [xiaolyuh/layering-cache#38]
项目中其他业务也要用到 redis，所以已经引用了spring-boot-starter-data-redis 的依赖，同时写了 spring 的 redis 配置，现在想用上 您的 layering-cache ，又要在配置文件中又写一套 redis 配置，感觉有点重复，因为都是用的 lettuce 连接的 redis，请问可以用什么方法让 layering-cache 直接用上已经有的 spring 中的 redis 配置。

![image](https://user-images.githubusercontent.com/28557735/111013408-39288c80-83da-11eb-8656-2775e13cbf66.png)

谢谢！

**Comment by xiaolyuh123** [comment]
不能，以前用的是一套，后来故意拆分开的，主要是为了隔离

发自我的iPhone
