### ISSUE TITLE
频繁出现 Command timed out after 1 minute(s)

### ISSUE THREAD

**Issue by HugoChanD** [xiaolyuh/layering-cache#39]
运行一段时间频繁出现这个 网络正常
2021-06-02 09:17:50.004 ERROR 1 --- [sage-1-thread-3] c.g.x.listener.RedisMessagePullTask      : layering-cache PULL 方式清楚一级缓存异常：Command timed out after 1 minute(s)

exauth_1   | com.github.xiaolyuh.redis.clinet.RedisClientException: Command timed out after 1 minute(s)
exauth_1   | 	at com.github.xiaolyuh.redis.clinet.SingleRedisClient.llen(SingleRedisClient.java:210)
exauth_1   | 	at com.github.xiaolyuh.listener.RedisMessageService.pullMessage(RedisMessageService.java:61)
exauth_1   | 	at com.github.xiaolyuh.listener.RedisMessageListener.message(RedisMessageListener.java:43)
exauth_1   | 	at com.github.xiaolyuh.listener.RedisMessageListener.message(RedisMessageListener.java:19)
exauth_1   | 	at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:185)
exauth_1   | 	at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:174)
exauth_1   | 	at io.lettuce.core.pubsub.PubSubCommandHandler.doNotifyMessage(PubSubCommandHandler.java:214)
exauth_1   | 	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:120)
exauth_1   | 	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
exauth_1   | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
exauth_1   | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
exauth_1   | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
exauth_1   | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
exauth_1   | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
exauth_1   | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
exauth_1   | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
exauth_1   | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
exauth_1   | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
exauth_1   | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
exauth_1   | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
exauth_1   | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
exauth_1   | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
exauth_1   | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
exauth_1   | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
exauth_1   | 	at java.lang.Thread.run(Thread.java:748)
exauth_1   | Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
exauth_1   | 	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
exauth_1   | 	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:120)
exauth_1   | 	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
exauth_1   | 	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
exauth_1   | 	at com.sun.proxy.$Proxy160.llen(Unknown Source)
exauth_1   | 	at com.github.xiaolyuh.redis.clinet.SingleRedisClient.llen(SingleRedisClient.java:206)
exauth_1   | 	... 24 more

**Comment by wutao8818** [comment]
我也随机出现这个提示，查了很多资料都说是lettuce的问题。是否可以替换为jedis客户端？

`> com.github.xiaolyuh.redis.clinet.RedisClientException: Command timed out after 1 minute(s)
        at com.github.xiaolyuh.redis.clinet.SingleRedisClient.llen(SingleRedisClient.java:238) ~[layering-cache-core-3.3.3.jar:?]
        at com.github.xiaolyuh.listener.RedisMessageService.pullMessage(RedisMessageService.java:61) ~[layering-cache-core-3.3.3.jar:?]
        at com.github.xiaolyuh.listener.RedisMessageListener.message(RedisMessageListener.java:40) [layering-cache-core-3.3.3.jar:?]
        at com.github.xiaolyuh.listener.RedisMessageListener.message(RedisMessageListener.java:14) [layering-cache-core-3.3.3.jar:?]
        at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:178) [lettuce-core-5.1.3.RELEASE.jar:?]
        at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:170) [lettuce-core-5.1.3.RELEASE.jar:?]
        at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:104) [lettuce-core-5.1.3.RELEASE.jar:?]
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:556) [lettuce-core-5.1.3.RELEASE.jar:?]
`

**Comment by xiaolyuh123** [comment]
最近有点忙，稍晚点我去看看

发自我的iPhone

**Comment by YiuTerran** [comment]
有进展么？

**Comment by wutao8818** [comment]
把layering cache 去掉了，回到直接redis一级缓存




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaolyuh/layering-cache"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaolyuh/layering-cache] 频繁出现 Command timed out after 1 minute(s) (#39)





 
有进展么？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaolyuh123** [comment]
Lettuce 同时支持共享连接和连接池方式来管理 Redis 连接。

共享连接：Lettuce 默认是共享连接，命令共享底层的 Native 连接。每次 Redis 超作时都会取到统一连接对象。
连接池：使用 GenericObjectPool 来管理连接池。每次 Redis 超作时，先看是否有空闲连接，有就用；没有就看是否到连接池最大上限就创建新连接；到了上限就根据配置看是等待还是直接返回null。
LettuceConnectionFactory#setShareNativeConnection(false); 可以关闭共享连接，开启线程池方式。
Lettuce 共享连接可以实现多线程并发访问相同的连接来执行 Redis 命令。但是，这样会导致请求过大时，某一个慢查询会导致一批请求慢查询。

原因就是用了共享连接，并发高了会向同一个连接发送消息，如果一个里面某个卡住了，就会导致它后面的全部卡住

参考下这个

**Comment by YiuTerran** [comment]
好的，谢谢

**Comment by xiaolyuh123** [comment]
你好 请问 使用 LettuceConnectionFactory#setShareNativeConnection(false);  方式后还会报time out吗
