### ISSUE TITLE
关于DEBUG日志输出的建议

### ISSUE THREAD

**Issue by osworks** [xiaolyuh/layering-cache#47]
![image](https://user-images.githubusercontent.com/4091000/146126037-627ec367-bdc9-4e18-8aa0-97e97943bb3a.png)

大佬，入上图。一级缓存的Key能不能也带上value值（value = "user:info2"），和二级缓存的KEY保持一致，测试验证的时候更明显好看一点。

**Comment by xiaolyuh123** [comment]
你这边如果有空 可以麻烦你帮忙改下吗 发起一个merge request就行
