### ISSUE TITLE
关于禁用一级缓存后（setEnableFirstCache(false)），相关日志输出还显示在操作一级缓存的问题

### ISSUE THREAD

**Issue by osworks** [xiaolyuh/layering-cache#48]
![image](https://user-images.githubusercontent.com/4091000/146306765-ea68b56a-b6bf-4fe6-a71d-02e67fdc0b35.png)
大佬，入上所示。禁用一级缓存后还显示在操作一级缓存，不知是日志显示的缺陷还是真的有在操作一级缓存呢？

**Comment by xiaolyuh123** [comment]
你直接改redis里面的数据 然后在请求缓存接口看数据变了没  变了就说明一级缓存已经禁用了


发自我的iPhone

**Comment by osworks** [comment]
经测试。一级缓存是禁用了的。只是日志输出有点误导人以为为什么禁用了一级缓存，日志显示还在操作一级缓存。
