### ISSUE TITLE
StatesService报错

### ISSUE THREAD

**Issue by icemoff** [xiaolyuh/layering-cache#5]
`
<dependency>
	<groupId>com.github.xiaolyuh</groupId>
	<artifactId>layering-cache-aspectj</artifactId>
	<version>2.0.0</version>
</dependency>
`

springboot版本2.1.1
控制台报错：
Could not read JSON: Unrecognized field "allowNullValues" (class com.github.xiaolyuh.setting.FirstCacheSetting), not marked as ignorable (5 known properties: "maximumSize", "expireMode", "expireTime", "initialCapacity", "timeUnit"])

定位代码报错位置为StatesService100行：
CacheStatsInfo cacheStats = (CacheStatsInfo)redisTemplate.opsForValue().get(redisKey);

**Comment by jimmycheng888** [comment]
页面jquery引用有问题

**Comment by xiaolyuh123** [comment]
在最新的2.0.1已经修复了

**Comment by xiaolyuh123** [comment]
路径后面在跟一个字符串

**Comment by xiaolyuh123** [comment]
在最新的2.0.1已经修复了
