### ISSUE TITLE
多台机器加载缓存会有问题吗

### ISSUE THREAD

**Issue by soye-yang** [xiaolyuh/layering-cache#52]
// 获取分布式锁去后台查询数据
                if (redisLock.lock()) {
                    T t = loaderAndPutValue(redisCacheKey, valueLoader, true);
                    if (logger.isDebugEnabled()) {
                        logger.debug("redis缓存 key= {} 从数据库获取数据完毕，唤醒所有等待线程", redisCacheKey.getKey());
                    }
                    // 唤醒线程
                    container.signalAll(redisCacheKey.getKey());
                    return t;
                }
                // 线程等待
                if (logger.isDebugEnabled()) {
                    logger.debug("redis缓存 key= {} 从数据库获取数据未获取到锁，进入等待状态，等待{}毫秒", redisCacheKey.getKey(), WAIT_TIME);
                }
                container.await(redisCacheKey.getKey(), WAIT_TIME);

这里如果这台机器都没有拿到锁。线程都等待了，那这个唤醒就只能等待超时了吧？那我理解和sleep就一样了

**Comment by xiaolyuh123** [comment]
没有问题，有个循环，有最大等待次数


发自我的iPhone

**Comment by soye-yang** [comment]
你的邮件已收到

**Comment by soye-yang** [comment]
> 没有问题，有个循环，有最大等待次数 发自我的iPhone
> […](#)
> 在 2022年1月21日，下午4:21，soye-yang ***@***.***> 写道： ﻿ // 获取分布式锁去后台查询数据 if (redisLock.lock()) { T t = loaderAndPutValue(redisCacheKey, valueLoader, true); if (logger.isDebugEnabled()) { logger.debug("redis缓存 key= {} 从数据库获取数据完毕，唤醒所有等待线程", redisCacheKey.getKey()); } // 唤醒线程 container.signalAll(redisCacheKey.getKey()); return t; } // 线程等待 if (logger.isDebugEnabled()) { logger.debug("redis缓存 key= {} 从数据库获取数据未获取到锁，进入等待状态，等待{}毫秒", redisCacheKey.getKey(), WAIT_TIME); } container.await(redisCacheKey.getKey(), WAIT_TIME); 这里如果这台机器都没有拿到锁。线程都等待了，那这个唤醒就只能等待超时了吧？那我理解和sleep就一样了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.

好的 谢谢。大部分实现都是用封装的FutureTask来实现这个锁等待 与 你这边直接用底层的LockSupport应该大同小异

**Comment by soye-yang** [comment]
你的邮件已收到
