### ISSUE TITLE
二级缓存不起作用？每次都查db去了

### ISSUE THREAD

**Issue by NorthrendSnow** [xiaolyuh/layering-cache#62]
版本3.4.3
设置CacheMode.ALL时，只要一级缓存过期（redis缓存存在），就会删除redis和一级缓存，然后查DB
![WechatIMG725](https://user-images.githubusercontent.com/28733784/164588420-dad8c063-d291-4aa8-9f26-4c6b4db927a1.jpeg)
![WechatIMG727](https://user-images.githubusercontent.com/28733784/164588431-9a9cb4de-14dd-4a9d-940f-7d284bd8abb5.jpeg)
设置CacheMode.SECOND时，每次调用都查DB，根本没走缓存
![WechatIMG726](https://user-images.githubusercontent.com/28733784/164588573-19169528-b2ec-4180-9edb-b3895c71f9f2.jpeg)

版本3.3.4也是如此，请问各位有木有遇到同样问题

**Comment by NorthrendSnow** [comment]
我配置的序列化器是Jackson，看了下源码，没有针对LocalDateTime等时间类型作处理，所以反序列化后得到null。。。只能自己实现个Jackson序列化器或者使用其他的（实测Protostuff没问题）-_-!

**Comment by xiaolyuh123** [comment]
你这是触发了缓存刷新，耳机缓存还有个配置你看下

发自我的iPhone

**Comment by NorthrendSnow** [comment]
> 你这是触发了缓存刷新，耳机缓存还有个配置你看下 发自我的iPhone
> […](#)
> 在 2022年4月22日，下午3:07，NorthrendSnow ***@***.***> 写道： ﻿ 我配置的序列化器是Jackson，看了下源码，没有针对LocalDateTime等时间类型作处理，所以反序列化后得到null。。。只能自己实现个Jackson序列化器或者使用其他的（实测Protostuff没问题）-_-! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

不是的，原因在2楼。缓存对象不带“java.time.XXX时间类型”就没问题
