### ISSUE TITLE
不支持哨兵吗，我通过host传哨兵和集群传哨兵列表都不生效

### ISSUE THREAD

**Issue by zxhchime** [xiaolyuh/layering-cache#64]

**Comment by zxhchime** [comment]
如果不支持哨兵，可能项目需要改架构了

**Comment by xiaolyuh123** [comment]
暂时没有支持哨兵
发自我的iPhone

**Comment by 1327681842** [comment]
你好，请问有支持主从、哨兵的计划吗？或者方便提供一下魔改的思路吗？谢谢

**Comment by zxhchime** [comment]
> 你好，请问有支持主从、哨兵的计划吗？或者方便提供一下魔改的思路吗？谢谢

没有呢，对这个项目还不是太熟悉

**Comment by xiaolyuh123** [comment]
你们有哨兵环境吗 用来测试下

**Comment by 1327681842** [comment]
不好意思，都在内网上

**Comment by zxhchime** [comment]
> 你们有哨兵环境吗 用来测试下

问一个比较蠢的问题。。

```
     @Cacheable(cacheNames = "XXX_", key = "#code",
                firstCache = @FirstCache(expireTime = 4, timeUnit = TimeUnit.SECONDS),
                secondaryCache = @SecondaryCache(expireTime = 10,
                                                                             preloadTime = 3,
                                                                             forceRefresh = true,
                                                                             timeUnit = TimeUnit.SECONDS),
               cacheMode = CacheMode.ALL)
    @Override
    public Type method(String code, int status)
```
我传不同的code进去内部缓存名没变，而且传相同code进去一级二级命中率都为0

**Comment by zxhchime** [comment]
> > 你们有哨兵环境吗 用来测试下
> 
> 问一个比较蠢的问题。。
> 
> ```
>      @Cacheable(cacheNames = "XXX_", key = "#code",
>                 firstCache = @FirstCache(expireTime = 4, timeUnit = TimeUnit.SECONDS),
>                 secondaryCache = @SecondaryCache(expireTime = 10,
>                                                                              preloadTime = 3,
>                                                                              forceRefresh = true,
>                                                                              timeUnit = TimeUnit.SECONDS),
>                cacheMode = CacheMode.ALL)
>     @Override
>     public Type method(String code, int status){
                Type type = TypeDao.query(code, status);
                return type;
       }
> ```
> 
> 我传不同的code进去内部缓存名没变，而且传相同code进去一级二级命中率都为0

**Comment by zxhchime** [comment]
> > > 你们有哨兵环境吗 用来测试下
> > 
> > 
> > 问一个比较蠢的问题。。
> > ```
> >      @Cacheable(cacheNames = "XXX_", key = "#code",
> >                 firstCache = @FirstCache(expireTime = 4, timeUnit = TimeUnit.SECONDS),
> >                 secondaryCache = @SecondaryCache(expireTime = 10,
> >                                                                              preloadTime = 3,
> >                                                                              forceRefresh = true,
> >                                                                              timeUnit = TimeUnit.SECONDS),
> >                cacheMode = CacheMode.ALL)
> >     @Override
> >     public Type method(String code, int status){ 
> >            Type type = TypeDao.query(code, status);
> >          return type;
> >   }
> > ```
> > 我传不同的code进去内部缓存名没变，而且传相同code进去一级二级命中率都为0

**Comment by 1327681842** [comment]
> > > > 你们有哨兵环境吗 用来测试下
> > > 
> > > 
> > > 问一个比较蠢的问题。。
> > > ```
> > >      @Cacheable(cacheNames = "XXX_", key = "#code",
> > >                 firstCache = @FirstCache(expireTime = 4, timeUnit = TimeUnit.SECONDS),
> > >                 secondaryCache = @SecondaryCache(expireTime = 10,
> > >                                                                              preloadTime = 3,
> > >                                                                              forceRefresh = true,
> > >                                                                              timeUnit = TimeUnit.SECONDS),
> > >                cacheMode = CacheMode.ALL)
> > >     @Override
> > >     public Type method(String code, int status){ 
> > >            Type type = TypeDao.query(code, status);
> > >          return type;
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我传不同的code进去内部缓存名没变，而且传相同code进去一级二级命中率都为0


我测试没有你说的问题

**Comment by zxhchime** [comment]
> > > > > 你们有哨兵环境吗 用来测试下
> > > > 
> > > > 
> > > > 问一个比较蠢的问题。。
> > > > ```
> > > >      @Cacheable(cacheNames = "XXX_", key = "#code",
> > > >                 firstCache = @FirstCache(expireTime = 4, timeUnit = TimeUnit.SECONDS),
> > > >                 secondaryCache = @SecondaryCache(expireTime = 10,
> > > >                                                                              preloadTime = 3,
> > > >                                                                              forceRefresh = true,
> > > >                                                                              timeUnit = TimeUnit.SECONDS),
> > > >                cacheMode = CacheMode.ALL)
> > > >     @Override
> > > >     public Type method(String code, int status){ 
> > > >            Type type = TypeDao.query(code, status);
> > > >          return type;
> > > >   }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我传不同的code进去内部缓存名没变，而且传相同code进去一级二级命中率都为0
> 
> 我测试没有你说的问题

好，我这边再琢磨琢磨

**Comment by 1327681842** [comment]
> cacheNames


你启动类有@EnableLayeringCache注解吗？你是在service层吗？或者时间调成分钟级，看看Redis里有可以吗？

**Comment by 1327681842** [comment]
> > > > > > 你们有哨兵环境吗 用来测试下
> > > > > 
> > > > > 
> > > > > 问一个比较蠢的问题。。
> > > > > ```
> > > > >      @Cacheable(cacheNames = "XXX_", key = "#code",
> > > > >                 firstCache = @FirstCache(expireTime = 4, timeUnit = TimeUnit.SECONDS),
> > > > >                 secondaryCache = @SecondaryCache(expireTime = 10,
> > > > >                                                                              preloadTime = 3,
> > > > >                                                                              forceRefresh = true,
> > > > >                                                                              timeUnit = TimeUnit.SECONDS),
> > > > >                cacheMode = CacheMode.ALL)
> > > > >     @Override
> > > > >     public Type method(String code, int status){ 
> > > > >            Type type = TypeDao.query(code, status);
> > > > >          return type;
> > > > >   }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 我传不同的code进去内部缓存名没变，而且传相同code进去一级二级命中率都为0
> > 
> > 
> > 我测试没有你说的问题
> 
> 好，我这边再琢磨琢磨



你启动类有@EnableLayeringCache注解吗？你是在service层吗？或者时间调成分钟级，看看Redis里有可以吗？

**Comment by zxhchime** [comment]
> > > > > > > 你们有哨兵环境吗 用来测试下
> > > > > > 
> > > > > > 
> > > > > > 问一个比较蠢的问题。。
> > > > > > ```
> > > > > >      @Cacheable(cacheNames = "XXX_", key = "#code",
> > > > > >                 firstCache = @FirstCache(expireTime = 4, timeUnit = TimeUnit.SECONDS),
> > > > > >                 secondaryCache = @SecondaryCache(expireTime = 10,
> > > > > >                                                                              preloadTime = 3,
> > > > > >                                                                              forceRefresh = true,
> > > > > >                                                                              timeUnit = TimeUnit.SECONDS),
> > > > > >                cacheMode = CacheMode.ALL)
> > > > > >     @Override
> > > > > >     public Type method(String code, int status){ 
> > > > > >            Type type = TypeDao.query(code, status);
> > > > > >          return type;
> > > > > >   }
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 我传不同的code进去内部缓存名没变，而且传相同code进去一级二级命中率都为0
> > > 
> > > 
> > > 我测试没有你说的问题
> > 
> > 
> > 好，我这边再琢磨琢磨
> 
> 你启动类有@EnableLayeringCache注解吗？你是在service层吗？或者时间调成分钟级，看看Redis里有可以吗？

![8BYI@81)1CYQ%WL9KX56X4L](https://user-images.githubusercontent.com/77111704/165059527-b1bbafeb-c97b-4ce2-b3d7-b73428933a33.png)

可能是我设置时间太短了。。，您这边的缓存key不是根据key="#code"变化的吗，我这边看见好像是个固定值，也不是集合，能解释一下原理吗，难道是放频道里了吗

**Comment by xiaolyuh123** [comment]
3.4.5版本已支持 sentinel

**Comment by xiaolyuh123** [comment]
我抽空了看看

发自我的iPhone
