### ISSUE TITLE
Protostuff 序列化后，再取值为空

### ISSUE THREAD

**Issue by lxf-lxf** [xiaolyuh/layering-cache#67]
传入的数组是空数组而不是null
![IMG_7408](https://user-images.githubusercontent.com/61101384/168302958-c819e8be-fc0c-4ca7-92f6-7176192368f3.JPG)
序列化存储后再取值后为null,重大影响
![IMG_7409](https://user-images.githubusercontent.com/61101384/168302915-c4fc0525-c3ae-4ce0-a677-b85f92e73266.JPG)

**Comment by xiaolyuh123** [comment]
3.4.7版本已解决
