### ISSUE TITLE
二级缓存随机不生效

### ISSUE THREAD

**Issue by LFDwater** [xiaolyuh/layering-cache#74]
调用函数后，一级缓存中确实存在缓存的数据，但是二级缓存，reids中没有查到任何信息
表现为二级缓存不生效（同样的函数，有时间是生效的0.0）

代码如图
![image](https://user-images.githubusercontent.com/38934315/188783658-5c3666a6-756f-49ff-8b47-3af27f874ea7.png)

**Comment by LFDwater** [comment]
![image](https://user-images.githubusercontent.com/38934315/188785550-5848acb0-b560-4b56-865b-e1df94ec65a9.png)
这个意思说的是设置用ALL的话，也只能一级或者二级中的一个生效吗

**Comment by xiaolyuh123** [comment]
ALL模式表示同时使用一二级缓存，你说的这种情况我没有复现

**Comment by LFDwater** [comment]
好的  感谢大佬  我自己在试试哈
