### ISSUE TITLE
缓存同步

### ISSUE THREAD

**Issue by tracine0513** [xiaolyuh/layering-cache#78]
我在代码中看到如下：
![image](https://user-images.githubusercontent.com/7425012/207570965-b8858514-6d0e-4f07-a5f5-2647d2747f3b.png)

但是我再实现原理中看到：
“每隔30秒会检查一下本地偏移量和远程偏移量是否一致，以此来解决redis pub/sub消息丢失或者断线问题。”

请问下，这个间隔二者描述是否有出入？

**Comment by tracine0513** [comment]
我的意思这个间隔时间

**Comment by xiaolyuh123** [comment]
这里是有出入，为了防止同一时刻大量请求同时访问到redis 所以把这里调整了一下

发自我的iPhone
