### ISSUE TITLE
secondaryCache不设置过期时间

### ISSUE THREAD

**Issue by zhmi19811015** [xiaolyuh/layering-cache#8]
设置expireTime = -1
出现io.lettuce.core.RedisCommandExecutionException: ERR invalid expire time in psetex

还有查询为null值可以设置过期时间，不为null不设置，如何处理

**Comment by xiaolyuh123** [comment]
这个必须设置过期时间，这个框架支持热点数据将要过期时的预加载，理论上可以一直不过期，所以不用担心过期问题。

如果允许缓存空值，可以给空置设置一个时间比，比如非空时缓存有效时间是10分钟，你的比值设置成10，那么空值的时候缓存有效时间就是1分钟。
