### ISSUE TITLE
关于LPUSH + LRange的疑问？

### ISSUE THREAD

**Issue by zxy1994** [xiaolyuh/layering-cache#85]
1. 缓存更新广播消息这块，为何不是用 RPUSH + LRange(oldOffset, maxOffset)的方式？是考虑了Lrange命令的时间复杂度吗？
2. 看源码是 LRange（0， maxOffset-oldOffset）的方式，这种方式拉到的消息顺序是反的（拉到多条消息的情况下）
3. 如果采用RPUSH的方式，拉到的消息顺序是没变的

**Comment by zxy1994** [comment]
● Lpush + Lrange是有bug的
● 因为这里都是从 0 ~ (maxOffset-oldOffset-1)获取元素，假设 old为3 max为4
● 在执行lrange前，又push了一个元素，max其实应该为5了，但是这里没取到最新的。出队命令为 lrange（0, 4-3-1）即 lrange(0, 0)拿到了最新push的元素。丢到了上一次push的元素
● 虽然还会触发一次拉消息。但新触发的动作也是 lrange(0, 5-4-1)，即 lrange(0, 0)；拿到的还是最新push的那个消息，上一次push的消息没拿到

有点刻舟求剑的感觉

**Comment by xiaolyuh123** [comment]
非常感谢您发现的问题，该问题将在3.4.8版本修复
