### ISSUE TITLE
cacheName不是支持SpEL的吗, 怎么没见实现呀

### ISSUE THREAD

**Issue by wolfleong** [xiaolyuh/layering-cache#86]
![image](https://github.com/xiaolyuh/layering-cache/assets/16425436/f4d427e0-4268-4efd-9b4f-bbe478f5d1b2)
![image](https://github.com/xiaolyuh/layering-cache/assets/16425436/0f3ebdfe-3627-40b3-b5f0-8a2aae6507c1)

**Comment by xiaolyuh123** [comment]
以前支持的 后来去掉了
