### ISSUE TITLE
关于兼容的一个建议

### ISSUE THREAD

**Issue by abelyliu** [xiaolyuh/layering-cache#9]
今天测试了下，遇到了一个小问题，再启动的时候发现com.github.xiaolyuh.aspect.LayeringAspect中CacheManager无法注入，导致应用启动失败。
后发现是，项目里开启了@EnableCaching注解，导致CacheManager因为bean id相同被覆盖，删除@EnableCaching或者在com.github.xiaolyuh.cache.config.LayeringCacheAutoConfig中CacheManager定义起个别名也可以启动成功。建议项目可以支持开启@EnableCaching情况，否则老项目比较难兼容。

**Comment by xiaolyuh123** [comment]
谢谢你的建议  我抽空处理一下

**Comment by xiaolyuh123** [comment]
谢谢你的建议  我抽空处理一下
