### ISSUE TITLE
如何使用指定线程池,异步刷新缓存

### ISSUE THREAD

**Issue by city2012** [xiaolyuh/layering-cache#97]
可以通过配置方式实现 通过指定线程池异步刷新一级缓存吗 ?

**Comment by city2012** [comment]
可以类似这样开启缓存异步更新吗?
layering:
  cache:
    # 开启异步更新缓存
    async-update: true
    # 异步更新缓存线程池大小
    async-update.pool-size: 10
    # 消息队列类型
    async-update.mq-type: redis
    # Redis消息队列配置
    async-update.mq.redis:
      host: localhost
      port: 6379
      password:
      database: 0

**Comment by xiaolyuh123** [comment]
目前还不支持
